name: Exigencies
main: com.teaminfinity.exigencies.Core
version: 1.4.1
description: >
             by Twyzl
author: Twyzl
authors: [Twyzl, GalaxyWolff]
softdepend: [GroupManager, PermissionsEx, Essentials]
commands:
  dos:
    description: command for sending several packets
  tempban:
    description: command for temporarily banning players
  delwarp:
    description: command for deleting warps
  warps:
    description: command for enlisting warps
  warp:
    description: command for warping
  setwarp:
    description: command for setting warps
  unmute:
    description: command for unmuting players
  mute:
    description: command for muting players
  sheepcannon:
    description: command for booming!
  spawn:
    description: command for teleporting to spawn
  setspawn:
    description: command for setting a spawnpoint
  jails:
    description: command for enlisting jails
  unjail:
    description: command for unjailing players
  jail:
    description: command for jailing players
  deljail:
    description: command for deleting jails
  setjail:
    description: command for setting jails
  tpall:
    description: command for teleporting all players to you
  tp:
    description: command for teleporting players
  ban:
    description: command for banning players
  echest:
    description: command for checking player enderchest
  invsee:
    description: command for checking player inventories
  check:
    description: command for checking associated players
  roll:
    description: command for generating random numbers
  killall:
    description: command for killing all mobs
  i:
    description: command for getting items
  pe:
    description: command for having a particle effect
  spawnmob:
    description: command for spawning mobs
  abuse:
    description: command for having some fun
  lag:
    description: command for viewing server data
  whois:
    description: command for viewing player data
  lore:
    description: command for adding lore to items
  rename:
    description: command for renaming items
  spam:
    description: command for showing text
  particleeffect:
    description: command for having a particle effect
  heal:
    description: command for healing players
  anvil:
    description: command for viewing an anvil
  gamemode:
    description: command for changing gamemodes
  gm:
    description: command for changing gamemodes
                    