name: Exigencies
main: com.teaminfinity.exigencies.Core
version: 1.4.1
description: >
             by Twyzl
author: Twyzl
authors: [Twyzl, GalaxyWolff]
softdepend: [GroupManager, PermissionsEx, Essentials]
commands:
  spawner:
    description: for changing spawner types
  kick:
    description: for kicing players
  storm:
    description: for setting the weather
  rain:
    description: for setting the weather
  sun:
    description: for setting the weather
  powertool:
    description: for changing powertools
  pt:
    description: for changing powertools
  night:
    description: for changing the time
  day:
    description: for changing the time
  dos:
    description: for sending several packets
  tempban:
    description: for temporarily banning players
  delwarp:
    description: for deleting warps
  warps:
    description: for enlisting warps
  warp:
    description: for warping
  setwarp:
    description: for setting warps
  unmute:
    description: for unmuting players
  mute:
    description: for muting players
  sheepcannon:
    description: for booming!
  spawn:
    description: for teleporting to spawn
  setspawn:
    description: for setting a spawnpoint
  jails:
    description: for enlisting jails
  unjail:
    description: for unjailing players
  jail:
    description: for jailing players
  deljail:
    description: for deleting jails
  setjail:
    description: for setting jails
  tpall:
    description: for teleporting all players to you
  tp:
    description: for teleporting players
  ban:
    description: for banning players
  echest:
    description: for checking player enderchest
  invsee:
    description: for checking player inventories
  check:
    description: for checking associated players
  roll:
    description: for generating random numbers
  killall:
    description: for killing all mobs
  i:
    description: for getting items
  pe:
    description: for having a particle effect
  spawnmob:
    description: for spawning mobs
  abuse:
    description: for having some fun
  lag:
    description: for viewing server data
  whois:
    description: for viewing player data
  lore:
    description: for adding lore to items
  rename:
    description: for renaming items
  spam:
    description: for showing text
  particleeffect:
    description: for having a particle effect
  heal:
    description: for healing players
  anvil:
    description: for viewing an anvil
  gamemode:
    description: for changing gamemodes
  gm:
    description: for changing gamemodes
                    